
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"   # Interfaz web de Jenkins
      - "50000:50000" # Puerto para agentes
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    user: root # Permite instalar plugins y manejar permisos fácilmente

volumes:
  jenkins_home:
